### ISSUE TITLE
SF2.7 - Twig Functions in Layout

### ISSUE THREAD

**Issue by mpclarkson** [lexik/LexikMailerBundle#49]
Hi there

Since upgrading to symfony 2.7 (beta 2), twig functions such as `{{ asset('path/to/file') })` and `{{absolute_url('path/to/file')}}` don't seem to work when included in the` base layout`.  

The specific error is `the twig function "asset" does not exist"`.

There does not seem to be a problem when twig functions are included in the email content.

Kind regards
Matt

**Comment by cedric-g** [comment]
Hi I'v not tested the bundle with SF 2.7 yet, but did you try that ?

```yml
# app/config/config.yml
lexik_mailer:
    templating_extensions:
        - 'twig.extension.trans'
        - 'twig.extension.assets'
```
