### ISSUE TITLE
Sonata Admin integration documentation

### ISSUE THREAD

**Issue by 12roar** [lexik/LexikMailerBundle#62]
Didn't understand why the bundle neglected to integrate with SonataAdmin. Even went so far creating my own services and child controllers, little did i know there was a configuration option available!!

Anyhow, the documentation should probably be tweaked, to include;

You can also integrate the bundle into SonataAdmin:

```yaml
# app/config/config.yml
lexik_mailer:
    sonata_integration: true  # enable integration (default is false)
```
